### ISSUE TITLE
A Qt account isn't needed to download the community version with Qt Installer

### ISSUE THREAD

**Issue by larpon** [ndesai/qml.guide#1]
Your QML QtQuick guide states:
`A qt.io account is needed to install`
If you plan on using the community version you can simply skip the registration. This might or might not be worth mentioning?

**Comment by ndesai** [comment]
Great, thanks @Larpon, I have updated the post. I was not aware of the "skip" button.

**Comment by larpon** [comment]
No problem - thanks for the guide!
